import { prisma } from "@/lib/prisma";
import { getAuthSession } from "@/lib/auth";
import { redirect } from "next/navigation";
import AINutritionCoach from "@/components/ai/AINutritionCoach";

export default async function AINutritionPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const session = await getAuthSession();

  if (!session?.user) return null;
  const memberProfile = await prisma.memberProfile.findUnique({
    where: { userId: session.user.id },
  });
  if (!memberProfile) return null;

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">AI Nutrition Coach</h1>
        <p className="text-gray-500 mt-1">
          Get a personalised Nigerian meal plan generated by Claude AI
        </p>
      </div>
      <AINutritionCoach
        memberId={memberProfile?.id ?? ""}
        memberData={{
          weightKg: memberProfile?.weightKg ?? null,
          heightCm: memberProfile?.heightCm ?? null,
          fitnessGoals: memberProfile?.fitnessGoals ?? [],
        }}
      />
    </div>
  );
}
