"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

interface AiUsageData {
  period: { days: number; since: string };
  summary: {
    totalCalls: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    estimatedCost: number;
  };
  byFeature: {
    feature: string;
    callCount: number;
    inputTokens: number;
    outputTokens: number;
  }[];
  dailyBreakdown: { date: string; count: number }[];
  topUsers: { userId: string; name: string; email: string; callCount: number }[];
}

const FEATURE_META: Record<string, { label: string; icon: string; color: string }> = {
  CHAT: { label: "AI Chat", icon: "💬", color: "#6366F1" },
  WORKOUT: { label: "Workout Coach", icon: "🏋️", color: "#8B5CF6" },
  NUTRITION: { label: "Nutrition Coach", icon: "🥗", color: "#10B981" },
  PROGRESS: { label: "Progress Analyzer", icon: "📊", color: "#F59E0B" },
};

export default function AiUsagePage() {
  const params = useParams<{ slug: string }>();
  const [data, setData] = useState<AiUsageData | null>(null);
  const [days, setDays] = useState(30);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/admin/ai-usage?days=${days}`)
      .then((r) => r.json())
      .then((d) => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, [days]);

  const maxDaily = data
    ? Math.max(...data.dailyBreakdown.map((d) => d.count), 1)
    : 1;

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900">AI Usage Analytics</h1>
          <p className="text-gray-500 text-sm mt-1">
            Monitor AI feature usage and estimated Anthropic API costs
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-sm text-gray-500">Last</span>
          {[7, 14, 30, 60, 90].map((d) => (
            <button
              key={d}
              id={`days-filter-${d}`}
              onClick={() => setDays(d)}
              className={`px-3 py-1.5 rounded-lg text-sm font-semibold transition-all ${
                days === d
                  ? "bg-indigo-600 text-white shadow-sm"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
              }`}
            >
              {d}d
            </button>
          ))}
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center h-48">
          <div className="w-8 h-8 border-3 border-indigo-600 border-t-transparent rounded-full animate-spin" />
        </div>
      ) : !data ? (
        <p className="text-center text-gray-400 py-16">Failed to load AI usage data.</p>
      ) : (
        <>
          {/* Summary Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              {
                label: "Total AI Calls",
                value: data.summary.totalCalls.toLocaleString(),
                icon: "🤖",
                sub: `Last ${days} days`,
                color: "#6366F1",
              },
              {
                label: "Input Tokens",
                value: (data.summary.totalInputTokens / 1000).toFixed(1) + "k",
                icon: "📥",
                sub: "Sent to Claude",
                color: "#8B5CF6",
              },
              {
                label: "Output Tokens",
                value: (data.summary.totalOutputTokens / 1000).toFixed(1) + "k",
                icon: "📤",
                sub: "Generated by Claude",
                color: "#10B981",
              },
              {
                label: "Est. Cost",
                value: `$${data.summary.estimatedCost.toFixed(2)}`,
                icon: "💰",
                sub: "Approximate USD",
                color: "#F59E0B",
              },
            ].map((card) => (
              <div
                key={card.label}
                className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm"
              >
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center text-xl mb-3"
                  style={{ background: `${card.color}15` }}
                >
                  {card.icon}
                </div>
                <p className="text-2xl font-black text-gray-900">{card.value}</p>
                <p className="text-xs font-semibold text-gray-500 mt-0.5">{card.label}</p>
                <p className="text-xs text-gray-400 mt-0.5">{card.sub}</p>
              </div>
            ))}
          </div>

          {/* By Feature + Top Users */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Feature breakdown */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <h2 className="font-bold text-gray-900 mb-4">Usage by Feature</h2>
              {data.byFeature.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-8">No AI calls recorded yet.</p>
              ) : (
                <div className="space-y-4">
                  {data.byFeature.map((f) => {
                    const meta = FEATURE_META[f.feature] ?? {
                      label: f.feature,
                      icon: "🤖",
                      color: "#6366F1",
                    };
                    const pct = data.summary.totalCalls
                      ? Math.round((f.callCount / data.summary.totalCalls) * 100)
                      : 0;
                    return (
                      <div key={f.feature}>
                        <div className="flex items-center justify-between mb-1">
                          <div className="flex items-center gap-2">
                            <span>{meta.icon}</span>
                            <span className="text-sm font-semibold text-gray-700">
                              {meta.label}
                            </span>
                          </div>
                          <span className="text-sm font-bold text-gray-900">
                            {f.callCount} calls
                          </span>
                        </div>
                        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div
                            className="h-full rounded-full transition-all duration-500"
                            style={{ width: `${pct}%`, background: meta.color }}
                          />
                        </div>
                        <p className="text-xs text-gray-400 mt-0.5">
                          {(f.inputTokens / 1000).toFixed(1)}k in /{" "}
                          {(f.outputTokens / 1000).toFixed(1)}k out
                        </p>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Top users */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <h2 className="font-bold text-gray-900 mb-4">Top Users by AI Calls</h2>
              {data.topUsers.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-8">No data yet.</p>
              ) : (
                <div className="space-y-3">
                  {data.topUsers.map((user, i) => (
                    <div
                      key={user.userId}
                      id={`ai-user-row-${user.userId}`}
                      className="flex items-center gap-3"
                    >
                      <span className="w-6 text-center text-xs font-bold text-gray-400">
                        {i + 1}
                      </span>
                      <div
                        className="w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-black uppercase"
                        style={{ background: "linear-gradient(135deg, #6366F1, #8B5CF6)" }}
                      >
                        {(user.name || user.email || "?")[0]}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-semibold text-gray-900 truncate">
                          {user.name || "Unnamed User"}
                        </p>
                        <p className="text-xs text-gray-400 truncate">{user.email}</p>
                      </div>
                      <span className="text-sm font-bold text-indigo-600">
                        {user.callCount}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Daily Sparkline */}
          {data.dailyBreakdown.length > 0 && (
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <h2 className="font-bold text-gray-900 mb-6">
                Daily AI Calls — Last {days} Days
              </h2>
              <div className="flex items-end gap-1 h-28">
                {data.dailyBreakdown.map((d) => {
                  const barH = Math.round((d.count / maxDaily) * 100);
                  return (
                    <div
                      key={d.date}
                      className="flex-1 group relative"
                      title={`${d.date}: ${d.count} calls`}
                    >
                      <div
                        className="w-full rounded-t-sm transition-all duration-300 hover:opacity-75"
                        style={{
                          height: `${Math.max(barH, 4)}%`,
                          background: "linear-gradient(to top, #6366F1, #8B5CF6)",
                        }}
                      />
                      {/* Tooltip */}
                      <div className="absolute -top-8 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs rounded px-2 py-1 whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10">
                        {d.count} call{d.count !== 1 ? "s" : ""}
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="flex justify-between text-xs text-gray-400 mt-2">
                <span>
                  {new Date(data.dailyBreakdown[0]?.date ?? "").toLocaleDateString("en-NG", {
                    month: "short",
                    day: "numeric",
                  })}
                </span>
                <span>
                  {new Date(
                    data.dailyBreakdown[data.dailyBreakdown.length - 1]?.date ?? ""
                  ).toLocaleDateString("en-NG", { month: "short", day: "numeric" })}
                </span>
              </div>
            </div>
          )}

          {data.summary.totalCalls === 0 && (
            <div className="text-center py-16 bg-white rounded-2xl border border-gray-100">
              <div className="text-5xl mb-4">🤖</div>
              <p className="font-bold text-gray-900">No AI usage recorded yet</p>
              <p className="text-gray-500 text-sm mt-1">
                Members will appear here once they use the AI coach features.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
}
